remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Jeremy Rossell
logo: /assets/img/icon.png
description: Welcome to my curriculum.
show_downloads: true
google_analytics:
theme:
